### ISSUE TITLE
Make UUID a non-default feature

### ISSUE THREAD

**Issue by russellbanks** [sunsided/async-tempfile-rs#2]
Currently if the UUID feature is not needed it has to be removed with `default-features = false`. Temporary files can be created with just a name, so it makes sense for UUID to be a non-default feature instead.

**Comment by sunsided** [comment]
Thanks for the observation. It'll be in the next release.

**Comment by sunsided** [comment]
Published in [0.5.0](https://github.com/sunsided/async-tempfile-rs/releases/tag/0.5.0).
